sudo: required
language: java
before_install:
    - chmod +x .travis/before_test.sh
    - chmod +x .travis/script.sh
    - echo "MAVEN_OPTS='-Xmx384m'" > ~/.mavenrc
install: .travis/before_test.sh
dist: trusty
cache:
  directories:
    - $HOME/.m2
jdk:
    - oraclejdk9
    - oraclejdk8
env:
    - AURORA=true
    - MARIA=5.5 PACKET=8M
    - MARIA=10.0 PACKET=8M
    - MARIA=10.1 PACKET=8M
    - MARIA=10.1 PACKET=20M
    - MARIA=10.1 PACKET=40M
    - MARIA=10.2 PACKET=8M
    - MARIA=10.2 PACKET=20M
    - MARIA=10.2 PACKET=40M
    - TYPE=MAXSCALE MAXSCALE_VERSION=2.0.2 MARIA=10.1 PACKET=40M
    - TYPE=REWRITE MARIA=10.1 PACKET=40M
    - TYPE=MULTI MARIA=10.1 PACKET=40M
    - TYPE=BULK_CLIENT MARIA=10.1 PACKET=40M
    - TYPE=NO_BULK_CLIENT MARIA=10.1 PACKET=40M
    - TYPE=NO_BULK_SERVER MARIA=10.1 PACKET=40M
    - COMPRESSION=false MARIA=10.1 PACKET=40M
    - TYPE=NO_BULK_SERVER MARIA=10.2 PACKET=40M
    - COMPRESSION=false MARIA=10.2 PACKET=40M
    - MYSQL=5.7 PACKET=8M
    - MYSQL=5.6 PACKET=8M
script: .travis/script.sh
